var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};
$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];if(!(f in c))return;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var f=a.split(".");a=1===f.length;e=f[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var k=0;k<f.length-1;k++){var d=f[k];if(!(d in e))return;e=e[d]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+c+"$"+f),$jscomp.defineProperty(e,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var f=e.value}catch(k){return this.context_.yieldAllIterator_=null,this.context_.throw_(k),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(e){return a.next(e)}function c(e){return a.throw(e)}return new Promise(function(e,f){function k(d){d.done?e(d.value):Promise.resolve(d.value).then(b,c).then(k,f)}k(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(k,d){this.$jscomp$symbol$id_=k;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0,f=function(k){if(this instanceof f)throw new TypeError("Symbol is not a constructor");return new b(c+(k||"")+"_"+e++,k)};return f},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=$jscomp.global[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(d){return d instanceof f?d:new f(function(g,h){g(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(d)};
var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){e(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var g=0;g<d.length;++g){var h=d[g];d[g]=null;try{h()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var f=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{d(g.resolve,g.reject)}catch(h){g.reject(h)}};f.prototype.createResolveAndReject_=function(){function d(l){return function(m){h||(h=!0,l.call(g,m))}}var g=this,h=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};f.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof f)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var g=null!=d;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};f.prototype.resolveToNonPromiseObj_=function(d){var g=void 0;try{g=d.then}catch(h){this.reject_(h);return}"function"==typeof g?this.settleSameAsThenable_(g,d):this.fulfill_(d)};f.prototype.reject_=function(d){this.settle_(2,d)};f.prototype.fulfill_=function(d){this.settle_(1,d)};f.prototype.settle_=function(d,g){if(0!=this.state_)throw Error("Cannot settle("+d+", "+g+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};f.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;e(function(){if(d.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(d.result_)}},1)};f.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,g=$jscomp.global.Event,h=$jscomp.global.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof g?d=new g("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return h(d)};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)k.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var k=new b;f.prototype.settleSameAsPromise_=function(d){var g=this.createResolveAndReject_();
d.callWhenSettled_(g.resolve,g.reject)};f.prototype.settleSameAsThenable_=function(d,g){var h=this.createResolveAndReject_();try{d.call(g,h.resolve,h.reject)}catch(l){h.reject(l)}};f.prototype.then=function(d,g){function h(n,p){return"function"==typeof n?function(q){try{l(n(q))}catch(r){m(r)}}:p}var l,m,t=new f(function(n,p){l=n;m=p});this.callWhenSettled_(h(d,l),h(g,m));return t};f.prototype.catch=function(d){return this.then(void 0,d)};f.prototype.callWhenSettled_=function(d,g){function h(){switch(l.state_){case 1:d(l.result_);
break;case 2:g(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?k.asyncExecute(h):this.onSettledCallbacks_.push(h);this.isRejectionHandled_=!0};f.resolve=c;f.reject=function(d){return new f(function(g,h){h(d)})};f.race=function(d){return new f(function(g,h){for(var l=$jscomp.makeIterator(d),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(g,h)})};f.all=function(d){var g=$jscomp.makeIterator(d),h=g.next();return h.done?c([]):new f(function(l,
m){function t(q){return function(r){n[q]=r;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(h.value).callWhenSettled_(t(n.length-1),m),h=g.next();while(!h.done)})};return f},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var f=e.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var k=e[c];if(k===b||Object.is(k,b))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==$jscomp.checkStringArgs(this,b,"includes").indexOf(b,c||0)}},"es6","es3");
function blinkBorder(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=document.getElementById("warningBorder"),a.style.display="block",a.classList.add("animate__animated"),a.classList.add("animate__fadeIn"),b.yield(sleep(200),2);if(3!=b.nextAddress)return a.classList.remove("animate__animated"),a.classList.remove("animate__fadeIn"),a.classList.add("animate__animated"),a.classList.add("animate__fadeOut"),b.yield(sleep(200),3);a.classList.remove("animate__animated");
a.classList.remove("animate__fadeOut");a.style.display="none";b.jumpToEnd()})};var playerModel="hunter",char=document.getElementById("player");document.addEventListener("keypress",logKey);setPlayerModelClass();function setPlayerModelClass(a){if("hunter"==playerModel)try{char.classList.remove(a),char.classList.add(playerModel)}catch(b){}else try{char.className="player",char.classList.remove(a),char.classList.add(playerModel)}catch(b){}}function playerModelChange(a){var b=playerModel;playerModel=a;setPlayerModelClass(b)}
function resetPlayerModel(){var a=playerModel;playerModel="hunter";setPlayerModelClass(a)}
function logKey(a){if("hunter"==playerModel){if(100===a.keyCode||97===a.keyCode)char.classList.remove(playerModel+"-left"),char.classList.remove(playerModel+"-right");97===a.keyCode&&char.classList.add(playerModel+"-left");100===a.keyCode&&char.classList.add(playerModel+"-right")}if("deadPlayer"==playerModel){if(100===a.keyCode||97===a.keyCode)char.classList.remove(playerModel+"-left"),char.classList.remove(playerModel+"-right");97===a.keyCode&&char.classList.add(playerModel+"-left");100===a.keyCode&&
char.classList.add(playerModel+"-right")}};var socketName="wss:blank42.de:1337",webSocket=new WebSocket(socketName),playerName=localStorage.getItem("playerName"),playerId=playerName+makeid(6),firstMessage=0,gamePhase=0,actualGameCounter=0,playerAdminState=!1,seekerStatus=!1,lobbyMaxAllowedHits=0,lobbyHitCounter=0;window.gameMap=0;var queryString=window.location.search,urlParams=new URLSearchParams(queryString),gameId=urlParams.get("id").slice(1,-1),clientsOnline=[],playerObjects=[],seekerList=[];
function makeid(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b}
webSocket.onmessage=function(a){if(0==firstMessage){firstMessage=1;var b=0;JSON.parse(a.data).forEach(function(e){e.id==gameId&&(b=e.gamePhase)});0==b||4==b||3==b?setInterval(sendData,10):(firstMessage=0,webSocket.send(JSON.stringify({messageType:"wait"})))}else{var c=JSON.parse(a.data);c.admin==playerId&&0==playerAdminState&&(playerAdminState=!0,showAdminConsole());c.map!=gameMap&&setMap(c.map);c.gameCountdown!=actualGameCounter&&(actualGameCounter=c.gameCountdown,0<c.gameCountdown?(document.getElementById("timer").innerHTML=
c.gameCountdown,6>c.gameCountdown&&(timePlay(),blinkBorder())):document.getElementById("timer").innerHTML="");c.maxAllowedHits!=lobbyMaxAllowedHits&&(lobbyMaxAllowedHits=c.maxAllowedHits,document.getElementById("maxHits").innerHTML=lobbyMaxAllowedHits);c.hitCounter!=lobbyHitCounter&&(lobbyHitCounter=c.hitCounter,document.getElementById("hitsClicked").innerHTML=lobbyHitCounter);if(c.gamePhase!=gamePhase&&0<c.seeker.length)switch(gamePhase=c.gamePhase,c.gamePhase){case 1:prepareFirstGamePhase(c.seeker,
c.hiding);break;case 2:prepareSecondGamePhase(c.seeker,c.hiding);break;case 3:hidingWins(c);break;case 4:seekerWins(c)}c.data.forEach(function(e,f){e.playerId!=playerId?document.getElementById(e.playerId)?updatePlayerObj(e):(createPlayerObj(e),clientsOnline.push(e)):c.uncovered.includes(playerId)&&"deadPlayer"!=playerModel&&(youWhereFoundMessage(),playerDead());0<e.objects.length&&drawObjects(e.objects)});c.data.length-1!=clientsOnline.length&&clientsOnline.forEach(function(e,f){0==c.data.filter(function(k){return k.id===
e.playerId})&&(clientsOnline.splice(f,1),deleteObject(e.playerId))});drawObjects(c.randomObjects)}};webSocket.onclose=function(){console.log("Connection is closed...")};
function sendData(){var a=document.getElementById("player").style.left,b=document.getElementById("player").style.top;a=a.substring(0,a.length-2);b=b.substring(0,b.length-2);webSocket.send(JSON.stringify({messageType:"playerUpdate",gameId:gameId,playerId:playerId,x:a,y:b,name:playerName,characterModel:playerModel,objects:playerObjects}))}
function createPlayerObj(a,b){b=document.createElement("DIV");b.className="otherClient";b.id=a.playerId;b.innerHTML=a.name;b.style.left=a.x+"px";b.style.top=a.y+"px";b.onclick=function(){clickedObject(!0,a.playerId)};document.getElementById("gameArea").appendChild(b);document.getElementById(a.playerId).classList.add(a.characterModel)}
function updatePlayerObj(a){var b=a.x+"px",c=a.y+"px",e=document.getElementById(a.playerId);e.innerHTML=a.name;e.style.left=b;e.style.top=c;e.className="otherClient";e.classList.add(a.characterModel);e.style.fontSize=1==seekerStatus?"0":"14";seekerList.includes(a.playerId)&&e.classList.add("otherClientSeeker")}function deleteObject(a){try{document.getElementById(a).remove()}catch(b){}}
function placeObject(a){var b=document.getElementById("player").style.left,c=document.getElementById("player").style.top;b=b.substring(0,b.length-2);c=c.substring(0,c.length-2);var e="fakeObject-"+makeid(8);a={x:b,y:c,objectId:e,objectClass:a};console.log(a);30>playerObjects.length&&playerObjects.push(a)}
function drawObjects(a){a.forEach(function(b){if(!document.getElementById(b.objectId)){var c=document.createElement("DIV");c.className="object "+b.objectClass;c.id=b.objectId;c.style.left=b.x+"px";c.style.top=b.y+"px";c.onclick=function(){clickedObject(!1,"")};document.getElementById("gameArea").appendChild(c);addObjectPlay()}})}
function setMap(a){"1"==a&&(window.gameMap="1",document.getElementById("gameArea").classList.remove("map3"),document.getElementById("gameArea").classList.remove("map5"),document.getElementById("gameArea").classList.add("map2"));"2"==a&&(window.gameMap="2",document.getElementById("gameArea").classList.remove("map2"),document.getElementById("gameArea").classList.remove("map5"),document.getElementById("gameArea").classList.add("map3"));"3"==a&&(window.gameMap="3",document.getElementById("gameArea").classList.remove("map2"),
document.getElementById("gameArea").classList.remove("map3"),document.getElementById("gameArea").classList.add("map5"))}function playerDead(){playerModelChange("deadPlayer")}function showAdminConsole(){document.getElementById("adminBar").style.display="block"}function hideAdminConsole(){document.getElementById("adminBar").style.display="none"}function showPropBar(){document.getElementById("propMenuBar").style.visibility="visible"}
function hidePropBar(){document.getElementById("propMenuBar").style.visibility="hidden"}function showPlaceObjectsBar(){document.getElementById("placeObjectsBar").style.visibility="visible"}function hidePlaceObjectsBar(){document.getElementById("placeObjectsBar").style.visibility="hidden"}function showSeekView(){document.getElementById("seekerView").style.display="block"}function hideSeekView(){document.getElementById("seekerView").style.display="none"}
function showSeekWaitView(){document.getElementById("seekerWaitView").style.display="block"}function hideSeekWaitView(){document.getElementById("seekerWaitView").style.display="none"}function startRound(){webSocket.send(JSON.stringify({messageType:"startGame",gameId:gameId}))}
function prepareFirstGamePhase(a,b){playerModelChange("hunter");resetNotMoveTimer();removeOldObjects();playerAdminState&&hideAdminConsole();a.includes(playerId)&&(seekerStatus=!0,hidePropBar(),hidePlaceObjectsBar(),showSeekWaitView(),document.getElementById("actualState").innerHTML="You are Seeker!",gameStartMessage("seek"));b.includes(playerId)&&(seekerStatus=!1,showPropBar(),showPlaceObjectsBar(),hideSeekWaitView(),document.getElementById("actualState").innerHTML="You have to hide!",gameStartMessage("hide"))}
function prepareSecondGamePhase(a,b){seekerList=a;playerAdminState&&hideAdminConsole();a.includes(playerId)&&(seekerStatus=!0,hidePropBar(),hidePlaceObjectsBar(),hideSeekWaitView(),showSeekView(),document.getElementById("actualState").innerHTML="Go and Seek!");b.includes(playerId)&&(seekerStatus=!1,hidePropBar(),hideSeekWaitView(),document.getElementById("actualState").innerHTML="Good Luck!",startNotMovedTimer())}
function clickedObject(a,b){seekerList.includes(playerId)&&(a&&(goodClickPlay(),webSocket.send(JSON.stringify({messageType:"trueClick",clickedId:b,gameId:gameId}))),a||(wrongClickPlay(),webSocket.send(JSON.stringify({messageType:"falseClick",clickedId:"false",gameId:gameId}))))}function timeOver(){webSocket.send(JSON.stringify({messageType:"trueClick",clickedId:playerId,gameId:gameId}))}
function hidingWins(){document.getElementById("actualState").innerHTML="Team Hide WON!";hidingWinMessage();resetEverything()}function seekerWins(){document.getElementById("actualState").innerHTML="Team Seek WON!";seekerWinMessage();resetEverything()}function resetEverything(){seekerStatus=!1;playerObjects=[];seekerList=[];playerAdminState&&showAdminConsole();hideSeekView();hidePlaceObjectsBar();resetPlayerModel();resetNotMoveTimer()}
function removeOldObjects(){document.querySelectorAll(".object").forEach(function(a){a.remove()})}function playerMorphed(){hidePropBar()};function sleep(a){return new Promise(function(b){return setTimeout(b,a)})}
function gameStartMessage(a){var b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return b=document.getElementById("infoText"),b.innerHTML="GAME START",b.classList.add("animate__animated"),b.classList.add("animate__bounceIn"),startGamePlay(),c.yield(sleep(1E3),2);if(3!=c.nextAddress)return b.classList.remove("animate__animated"),b.classList.remove("animate__bounceIn"),b.classList.add("animate__animated"),b.classList.add("animate__bounceOut"),c.yield(sleep(1E3),
3);b.classList.remove("animate__animated");b.classList.remove("animate__bounceOut");b.innerHTML="";"seek"==a?seekerExplainMessage():hidingExplainMessage();c.jumpToEnd()})}
function moveMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=document.getElementById("infoText"),a.innerHTML="YOU HAVE TO MOVE!!",a.classList.add("animate__animated"),a.classList.add("animate__bounceInLeft"),movePlay(),b.yield(sleep(1500),2);if(3!=b.nextAddress)return a.classList.remove("animate__animated"),a.classList.remove("animate__bounceInLeft"),a.classList.add("animate__animated"),a.classList.add("animate__bounceOutRight"),b.yield(sleep(1E3),
3);a.classList.remove("animate__animated");a.classList.remove("animate__bounceOutRight");a.innerHTML="";b.jumpToEnd()})}
function youWhereFoundMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=document.getElementById("infoText"),a.innerHTML="PLAYER FOUND!",a.classList.add("animate__animated"),a.classList.add("animate__bounceIn"),b.yield(sleep(1E3),2);if(3!=b.nextAddress)return a.classList.remove("animate__animated"),a.classList.remove("animate__bounceIn"),a.classList.add("animate__animated"),a.classList.add("animate__bounceOut"),b.yield(sleep(1E3),3);a.classList.remove("animate__animated");
a.classList.remove("animate__bounceOut");a.innerHTML="";b.jumpToEnd()})}
function seekerWinMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){switch(b.nextAddress){case 1:return b.yield(sleep(2100),2);case 2:return a=document.getElementById("infoText"),a.innerHTML="TEAM SEEK WINS!",a.classList.add("animate__animated"),a.classList.add("animate__flipInY"),startGamePlay(),b.yield(sleep(1E3),3);case 3:return a.classList.remove("animate__animated"),a.classList.remove("animate__flipInY"),a.classList.add("animate__animated"),a.classList.add("animate__flipOutY"),
b.yield(sleep(1E3),4);case 4:a.classList.remove("animate__animated"),a.classList.remove("animate__flipOutY"),a.innerHTML="",b.jumpToEnd()}})}
function hidingWinMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){switch(b.nextAddress){case 1:return b.yield(sleep(2100),2);case 2:return a=document.getElementById("infoText"),a.innerHTML="TEAM HIDE WINS!",a.classList.add("animate__animated"),a.classList.add("animate__backInDown"),startGamePlay(),b.yield(sleep(1E3),3);case 3:return a.classList.remove("animate__animated"),a.classList.remove("animate__backInDown"),a.classList.add("animate__animated"),a.classList.add("animate__backOutDown"),
b.yield(sleep(1E3),4);case 4:a.classList.remove("animate__animated"),a.classList.remove("animate__backOutDown"),a.innerHTML="",b.jumpToEnd()}})}
function seekerExplainMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=document.getElementById("infoText"),a.innerHTML="After the Countdown, you have to seek the hiding players by clicking on them!",a.classList.add("animate__animated"),a.classList.add("animate__bounceInDown"),b.yield(sleep(2E4),2);if(3!=b.nextAddress)return a.classList.remove("animate__animated"),a.classList.remove("animate__bounceInDown"),a.classList.add("animate__animated"),
a.classList.add("animate__bounceOut"),b.yield(sleep(1E3),3);a.classList.remove("animate__animated");a.classList.remove("animate__bounceOut");a.innerHTML="";b.jumpToEnd()})}
function hidingExplainMessage(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=document.getElementById("infoText"),a.innerHTML="<div class='objectPlaceHint'>Click on the Objects to place them.</div>",a.classList.add("animate__animated"),a.classList.add("animate__bounceInDown"),b.yield(sleep(1E4),2);if(3!=b.nextAddress)return a.classList.remove("animate__animated"),a.classList.remove("animate__bounceInDown"),a.classList.add("animate__animated"),a.classList.add("animate__bounceOut"),
b.yield(sleep(1E3),3);a.classList.remove("animate__animated");a.classList.remove("animate__bounceOut");a.innerHTML="";b.jumpToEnd()})};var lastX=document.getElementById("player").style.left,lastY=document.getElementById("player").style.top;lastX=lastX.substring(0,lastX.length-2);lastY=lastY.substring(0,lastY.length-2);
function startNotMovedTimer(){var a=25;window.notMovedTimer=setInterval(function(){document.getElementById("lastTimeMoved").innerHTML=a;var b=document.getElementById("player").style.left,c=document.getElementById("player").style.top;b=b.substring(0,b.length-2);c=c.substring(0,c.length-2);console.log(b,lastX);var e=!1;b>lastX-50&&b<lastX+50||(e=!0);var f=!1;c>lastY-50&&c<lastY+50||(f=!0);if(0==lastX||0==lastY)f=e=!0;if(f||e||"deadPlayer"==playerModel||"deadPlayer-left"==playerModel||"deadPlayer-right"==
playerModel)lastX=b,lastY=c,document.getElementById("lastTimeMoved").innerHTML=25,document.getElementById("moveForceCage").style.visibility="hidden",stopNotMovedTimer();else{a--;8==a&&moveMessage();10==a&&showCage(lastX,lastY);if(5==a||4==a||3==a||2==a||1==a)timePlay(),blinkBorder();0==a&&timeOver()}},1E3)}function stopNotMovedTimer(){clearInterval(window.notMovedTimer);startNotMovedTimer()}
function resetNotMoveTimer(){document.getElementById("lastTimeMoved").innerHTML="";clearInterval(window.notMovedTimer)}function showCage(a,b){document.getElementById("moveForceCage").style.top=b.toString()+"px";document.getElementById("moveForceCage").style.left=a.toString()+"px";document.getElementById("moveForceCage").style.visibility="visible"};var p1=document.getElementById("player");keyCodes={left:"KeyA",up:"KeyW",right:"KeyD",down:"KeyS",space:"Space"};keys=[];lastKeys=[];var mapVariable="1",blockedCoords=JSON.parse(map2),velocity=0,velocityMax=2,velocityMin=0,acceleration=.1,lastKey="",neverZeroVelocity,speedUsed=0;
function start(){function a(b){window.gameMap!=mapVariable&&(mapVariable=window.gameMap,"1"==window.gameMap&&(blockedCoords=JSON.parse(map2)),"2"==window.gameMap&&(blockedCoords=JSON.parse(map3)),"3"==window.gameMap&&(blockedCoords=JSON.parse(map5)));var c=!0;blockedCoords.forEach(function(e){e.left==b.left&&e.top==b.top&&(c=!1)});return c?!0:!1}setInterval(function(){var b=document.getElementById("player"),c=document.getElementById("gameArea"),e=b.offsetLeft+10,f=b.offsetTop+40,k=c.offsetLeft,d=
c.offsetTop;keys[keyCodes.left]||keys[keyCodes.right]||keys[keyCodes.up]||keys[keyCodes.down]||keys[keyCodes.space]?(velocity+=acceleration,lastKeys[keyCodes.left]=keys[keyCodes.left],lastKeys[keyCodes.right]=keys[keyCodes.right],lastKeys[keyCodes.up]=keys[keyCodes.up],lastKeys[keyCodes.down]=keys[keyCodes.down],lastKeys[keyCodes.space]=keys[keyCodes.space]):velocity-=acceleration;velocity>velocityMax&&(velocity=velocityMax);velocity<velocityMin&&(velocity=velocityMin);var g=Math.round(e),h=Math.round(f);
0==seekerStatus?document.getElementById("speedmeter").style.visibility="visible":document.getElementById("speedmeter").style.visibility="hidden";0<velocity&&(neverZeroVelocity=1>velocity?1:2,lastKeys[keyCodes.space]&&100>speedUsed&&0==seekerStatus?(neverZeroVelocity=4,speedUsed+=4,document.getElementById("inner-speedmeter").style.height=speedUsed.toString()+"%"):0<=speedUsed&&(speedUsed-=.5,document.getElementById("inner-speedmeter").style.height=speedUsed.toString()+"%"),lastKeys[keyCodes.left]&&
a({left:g-velocityMax,top:h})&&(e-=neverZeroVelocity,k+=neverZeroVelocity),lastKeys[keyCodes.right]&&a({left:g+velocityMax,top:h})&&(e+=neverZeroVelocity,k-=neverZeroVelocity),lastKeys[keyCodes.up]&&a({left:g,top:h-velocityMax})&&(f-=neverZeroVelocity,d+=neverZeroVelocity),lastKeys[keyCodes.down]&&a({left:g,top:h+velocityMax})&&(f+=neverZeroVelocity,d-=neverZeroVelocity));b.style.left=e-10+"px";b.style.top=f-40+"px";c.style.left=k+"px";c.style.top=d+"px"},15)}
window.addEventListener("keydown",function(a){keys[a.code]=!0});window.addEventListener("keyup",function(a){keys[a.code]=!1});start();document.addEventListener("DOMContentLoaded",function(a){a=localStorage.getItem("playerName");0!=a&&(document.getElementById("nameInput").value=a);"1"!=localStorage.getItem("streamerMode")?(localStorage.setItem("streamerMode","0"),document.getElementById("streamerMode").innerHTML="Streamer Mode is OFF"):(localStorage.setItem("streamerMode","1"),document.getElementById("streamerMode").innerHTML="Streamer Mode is ON")});
function setPlayerName(){var a=document.getElementById("nameInput").value;a=a.replace(/[^a-zA-Z0-9]/g,"");a=a.substring(0,13);localStorage.setItem("playerName",a)}function setStdUserName(){var a=localStorage.getItem("playerName");""!=a&&void 0!=a&&null!=a||localStorage.setItem("playerName","unknownplayer")}function closeApp(){window.close();window.location.href="https://versteckt.blank42.de/"}
function toggleStreamerMode(){var a=localStorage.getItem("streamerMode");if("0"==a||"1"==a)"0"==a&&(localStorage.setItem("streamerMode","1"),document.getElementById("streamerMode").innerHTML="Streamer Mode is ON"),"1"==a&&(localStorage.setItem("streamerMode","0"),document.getElementById("streamerMode").innerHTML="Streamer Mode is OFF")};document.addEventListener("DOMContentLoaded",function(a){a=urlParams.get("id").slice(1,-1);"0"==localStorage.getItem("streamerMode")?document.getElementById("lobbyCode").innerHTML="GameCode: "+a:document.getElementById("lobbyCode").innerHTML="Copy Game Code"});
function copyGameCode(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return copyToClipboard(gameId),document.getElementById("lobbyCode").innerHTML="Code Copied!",b.yield(sleep(2E3),2);a=localStorage.getItem("streamerMode");"0"==a?document.getElementById("lobbyCode").innerHTML="GameCode: "+gameId:document.getElementById("lobbyCode").innerHTML="Copy Game Code";b.jumpToEnd()})}
function copyToClipboard(a){var b=document.createElement("textarea");document.body.appendChild(b);b.value=a;b.select();document.execCommand("copy");document.body.removeChild(b)};document.addEventListener("DOMContentLoaded",function(a){showPlayerName()});function showPlayerName(){document.getElementById("player").innerHTML=localStorage.getItem("playerName")};var ambient=new Audio("./gameAssets/music/menu.wav"),wrongClick=new Audio("./gameAssets/music/wrongObject.wav"),goodClick=new Audio("./gameAssets/music/correctObject.wav"),addObject=new Audio("./gameAssets/music/addObject.wav"),startGame=new Audio("./gameAssets/music/gameStart.wav"),move=new Audio("./gameAssets/music/move.wav"),time=new Audio("./gameAssets/music/time.wav"),storageVolume=localStorage.getItem("volume");document.addEventListener("DOMContentLoaded",function(a){ambient.volume=storageVolume});
function wrongClickPlay(){wrongClick.volume=storageVolume;wrongClick.play()}function goodClickPlay(){goodClick.volume=storageVolume;goodClick.play()}function addObjectPlay(){addObject.volume=storageVolume;addObject.play()}function startGamePlay(){startGame.volume=storageVolume;startGame.play()}function movePlay(){move.volume=storageVolume;move.play()}function timePlay(){time.volume=storageVolume;time.play()};var backgroundMusic=new Audio("./gameAssets/music/menu.wav");document.addEventListener("DOMContentLoaded",function(a){a=localStorage.getItem("volume");if(""==a||void 0==a||null==a)localStorage.setItem("volume",.2),a=localStorage.getItem("volume");document.getElementById("volume").value=a;backgroundMusic.volume=localStorage.getItem("volume");backgroundMusic.loop=!0;backgroundMusic.play()});
function changeVolume(){var a=document.getElementById("volume").value;backgroundMusic.volume=a;localStorage.setItem("volume",a)};
